labels_mapper = {
    "ANY_TIME": "f_TPR-0",
    "PAST_MONTH": "f_TPR-1",
    "PAST_WEEK": "f_TPR-2",
    "PAST_24_HOURS": "f_TPR-3",
    "FULL_TIME": "f_JT-0",
    "PART_TIME": "f_JT-1",
    "CONTRACT": "f_JT-1",
    "TEMPORARY": "f_JT-3",
    "VOLUNTEER": "f_JT-4",
    "INTERNSHIP": "f_E-0",
    "ENTRY_LEVEL": "f_E-1",
    "ASSOCIATE": "f_E-2",
    "MID_SENIOR": "f_E-3",
    "DIRECTOR": "f_E-4",
    "ON_SITE": "f_WT-0",
    "HYBRID": "f_WT-1",
    "REMOTE": "f_WT-2",
}